FROM node:20-bullseye AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --no-audit --no-fund

# Build Next.js project (embed NEXT_PUBLIC_* at build time)
FROM node:20-bullseye AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time environment variables (all 40 variables)
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG SUPABASE_SERVICE_ROLE_KEY
ARG NEXT_PUBLIC_SITE_URL
ARG SERPAPI_KEY
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG SHOTSTACK_API_KEY
ARG SHOTSTACK_ENDPOINT
ARG OPENAI_API_KEY
ARG ANTHROPIC_API_KEY
ARG ELEVENLABS_API_KEY
ARG FAL_API_KEY
ARG DEEPL_API_KEY
ARG LEONARDO_API_KEY
ARG IDEOGRAM_API_KEY
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG YOUTUBE_API_KEY
ARG SUPADATA_API_KEY
ARG GOOGLE_AI_API_KEY
ARG GOOGLE_API_KEY
ARG VOICEMAKER_API_KEY
ARG FISH_AUDIO_API_KEY
ARG MINIMAX_GROUP_ID
ARG MINIMAX_API_KEY
ARG PERPLEXITY_API_KEY
ARG FIRECRAWL_API_KEY
ARG REPLICATE_API_TOKEN
ARG FAL_KEY
ARG GEMINI_API_KEY
ARG PIXABAY_API_KEY
ARG PEXELS_API_KEY
ARG VOICES_ELEVENLABS_API_KEY
ARG STORYBLOCKS_PUBLIC_API_KEY
ARG STORYBLOCKS_PRIVATE_API_KEY
ARG GOOGLE_CLOUD_PROJECT_ID
ARG GOOGLE_APPLICATION_CREDENTIALS

ENV NODE_ENV=production
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
ENV SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV SERPAPI_KEY=${SERPAPI_KEY}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV SHOTSTACK_API_KEY=${SHOTSTACK_API_KEY}
ENV SHOTSTACK_ENDPOINT=${SHOTSTACK_ENDPOINT}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
ENV ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
ENV FAL_API_KEY=${FAL_API_KEY}
ENV DEEPL_API_KEY=${DEEPL_API_KEY}
ENV LEONARDO_API_KEY=${LEONARDO_API_KEY}
ENV IDEOGRAM_API_KEY=${IDEOGRAM_API_KEY}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
ENV SUPADATA_API_KEY=${SUPADATA_API_KEY}
ENV GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
ENV GOOGLE_API_KEY=${GOOGLE_API_KEY}
ENV VOICEMAKER_API_KEY=${VOICEMAKER_API_KEY}
ENV FISH_AUDIO_API_KEY=${FISH_AUDIO_API_KEY}
ENV MINIMAX_GROUP_ID=${MINIMAX_GROUP_ID}
ENV MINIMAX_API_KEY=${MINIMAX_API_KEY}
ENV PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
ENV FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
ENV REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
ENV FAL_KEY=${FAL_KEY}
ENV GEMINI_API_KEY=${GEMINI_API_KEY}
ENV PIXABAY_API_KEY=${PIXABAY_API_KEY}
ENV PEXELS_API_KEY=${PEXELS_API_KEY}
ENV VOICES_ELEVENLABS_API_KEY=${VOICES_ELEVENLABS_API_KEY}
ENV STORYBLOCKS_PUBLIC_API_KEY=${STORYBLOCKS_PUBLIC_API_KEY}
ENV STORYBLOCKS_PRIVATE_API_KEY=${STORYBLOCKS_PRIVATE_API_KEY}
ENV GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
ENV GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}

RUN npm run build

# Production runner
FROM node:20-bullseye AS runner
RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 8080
CMD ["sh", "-c", "npm run start -- --port ${PORT:-8080} --hostname 0.0.0.0"]

